version: '3.8'

services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: palyoplotbase
      MYSQL_USER: pbuser
      MYSQL_PASSWORD: 'ecs.open.pb.2024'
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data_prod:/var/lib/mysql

  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.production
    environment:
      - RUNNING_IN_DOCKER=True
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data_prod:
