# Generated by Django 5.1.3 on 2024-11-13 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('column_order', models.IntegerField()),
                ('data_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'csv_columns',
            },
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField()),
                ('display_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'csv_files',
            },
        ),
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('value', models.TextField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='myapi.csvcolumn')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='myapi.csvfile')),
            ],
            options={
                'db_table': 'csv_data',
            },
        ),
        migrations.AddField(
            model_name='csvcolumn',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='myapi.csvfile'),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('dataset_type', models.CharField(max_length=50)),
                ('csv_data', models.JSONField(blank=True, null=True)),
                ('visualization_pref', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_data', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GraphImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_data', models.ImageField(upload_to='graph_images/')),
                ('metadata', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'graph_images',
            },
        ),
        migrations.CreateModel(
            name='VisualizationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_type', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('additional_options', models.JSONField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualization_prefs', to='myapi.csvfile')),
                ('x_axis_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_axis_visualizations', to='myapi.csvcolumn')),
                ('y_axis_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_axis_visualizations', to='myapi.csvcolumn')),
            ],
            options={
                'db_table': 'visualization_preferences',
            },
        ),
    ]
