# Generated by Django 5.1.3 on 2024-11-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_dataset_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
