# Generated by Django 5.1.3 on 2024-11-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_dataset_image_data_csvcolumn_csvdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvcolumn',
            name='data_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visualizationpreferences',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
