# Generated by Django 5.1.3 on 2024-11-13 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_csvcolumn_data_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_data', models.ImageField(upload_to='graph_images/')),
                ('metadata', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'graph_images',
            },
        ),
    ]
